# Project information
site_name: Koushik's Blog
site_description: My Online Portfolio
site_author: Sai Koushik
site_url: https://sai-koushik-macha.github.io/

# Repository
repo_name: sai-koushik-macha/sai-koushik-macha.github.io
repo_url: https://github.com/sai-koushik-macha/sai-koushik-macha.github.io

# Theme settings
theme:
  name: "material"
  language: en
  icon:
    logo: "fontawesome/solid/feather"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs

# Nav
nav:
  - Home: index.md
  - Vim Editor:
      - Vim Basics: vim/vim-basics.md

extra_css: [extra.css]

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/sai-koushik-macha"
    - icon: "fontawesome/brands/linkedin"
      link: "https://www.linkedin.com/in/sai-koushik-macha-75ab51199/"
